[General]
background="images/background.png"
backgrounds="159510-Plexus-network-abstract-line-art-connectivity-dots-digital-2274747425.png,2223306-4288509887.jpg,6383617-1204388685.jpg,digital-world-map-connectivity-pipglxa20v26472h-2361656749.jpg,world-map-cyber-security-ivcowv89j1g1ff4m-2830473202.jpg"
dateFormat="dddd, dd MMMM yyyy"
